title: Ideas: Occasionally Good
description: A blog about, well, not much really
author: B. Cooney
github: https://github.com/bcooney
about: Mi neurosis es su neurosis.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/agusmakmun
    - text: XML Feed
      url: /feed.xml
url: "https://bcooney.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
